### ISSUE TITLE
プログラムの実行時のエラー

### ISSUE THREAD

**Issue by 20LeeBrian1** [naoyat/solitaire-solver#1]
私がccファイルを実行すると、うまくいきませんでした。 それを修正してください。

![an error uh oh](https://user-images.githubusercontent.com/35016860/34495325-96bfd1dc-efa9-11e7-8ba3-3614b97fb54e.PNG)

**Comment by naoyat** [comment]
ccファイルは実行ファイルではありません（C++で書かれたソースコードです）。
makeしてください。

**Comment by 20LeeBrian1** [comment]
申し訳ありませんが、私は知らなかった。 私はここで新しいので、私はあなたがこれからビデオを作ることができるかどうか疑問に思っています。

**Comment by naoyat** [comment]
動画を作る機能はありません。

**Comment by 20LeeBrian1** [comment]
私はちょうど尋ねていた

**Comment by 20LeeBrian1** [comment]
問題があれば、少なくとも私を助けることができます

**Comment by 20LeeBrian1** [comment]
私は気にするつもりはありませんでしたが、私に誓ってはいけません。 私は実際にプロジェクトを使うのはそれほど良いことではありません。
