### ISSUE TITLE
Running python files, but it didn't do a thing!

### ISSUE THREAD

**Issue by 20LeeBrian1** [naoyat/solitaire-solver#2]
免責事項：これは英語ですので、私が何を言っているのかをご理解いただきたいと思います。

I tried running python files, but it is missing one of the modules. For example, 

![capture](https://user-images.githubusercontent.com/35016860/34546399-6b76131a-f0a8-11e7-87fe-8bca8a563208.PNG)

I am not sure exactly why. Hope you understand what I am saying.

Do I have to download some kind of extension to support the python modules? I am using Python 2 to do it.

**Comment by naoyat** [comment]
I wrote this in Python 2, so hopefully you don't have to modify the code, but yes, you need to install some python modules by yourself (pip install xxx): numpy, keras, PIL (pillow) and click.

In case you're reading this via machine translation, please note that CLICK is the name of the module you need to install.
