### ISSUE TITLE
Running PY files

### ISSUE THREAD

**Issue by 20LeeBrian1** [naoyat/solitaire-solver#3]
In English?

Since you have 4 py files, I noticed there are issues here.

When I tried running freecell_game_loader.py, I noticed two errors here:
![capture](https://user-images.githubusercontent.com/35016860/35177317-2571eadc-fd33-11e7-8b01-97ea4e8c9354.PNG)
When I tried running freecell_image_loader.py, I noticed an error here:
![capture 2](https://user-images.githubusercontent.com/35016860/35177340-52e2bdb6-fd33-11e7-9f4b-1803c9feac7e.PNG)
When I tried running freecell_model.py, I noticed an error here:
![capture 3](https://user-images.githubusercontent.com/35016860/35177371-8ec0a5aa-fd33-11e7-9002-e19700172fa2.PNG)
When I tried running freecell_solver.py, I noticed an error here:
![capture 4](https://user-images.githubusercontent.com/35016860/35177377-b3ceddd0-fd33-11e7-8c59-5ccf91540835.PNG)

Hopefully you can understand what I mean. Here, I am using Python 3.6.4. Can you at least figure out the problem here? I know that you are tired responding to me, but like I said, I am new here and I just wanted to run certain files, but I observed certain errors. Sorry about my poor grammar, at least you can help me. Thank you.

**Comment by 20LeeBrian1** [comment]
Oh, by the way, I am using the desktop app Eclipse.

**Comment by naoyat** [comment]
It's because I wrote this in Python 2.7.
If you want to run it on Python 3.x, you just have to put arguments of 'print' in parentheses as follows:
```
print _tmp --> print(_tmp)
print loss, acc --> print(loss, acc)
```

**Comment by naoyat** [comment]
I just committed a patch to do this. Please 'git pull' to reflect my modifications.
