### ISSUE TITLE
Running TriPeaks Solver

### ISSUE THREAD

**Issue by 20LeeBrian1** [naoyat/solitaire-solver#5]
While I was trying to run the command $ cat <<EOF > tripeaks_sample_2.txt, it works. But when I tried to run $ ./TripeaksSolver tripeaks_sample_2.txt, it says that ./TripeaksSolver: no such file or directory.

![screenshot from 2018-09-29 08-05-43](https://user-images.githubusercontent.com/35016860/46247324-81949100-c3be-11e8-88bb-daab74374881.png)

**Comment by naoyat** [comment]
You should build TripeaksSolver executable.
```
make TripeaksSolver
```
(Please google it if you're not familiar with "make" and "Makefile".)
